version: '2'

services:
  vp0:
    extends:
      file: common.yml
      service: vp
    hostname: vp0
    ports:
      - "7050:7050"
    environment:
      - CORE_PEER_ID=vp0
  vp1:
    extends:
      file: common.yml
      service: vp
    hostname: vp1
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    links:
      - vp0
  vp2:
    extends:
      file: common.yml
      service: vp
    hostname: vp2
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    links:
      - vp0
  vp3:
    extends:
      file: common.yml
      service: vp
    hostname: vp3
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    links:
      - vp0

